### PR TITLE
make the game great/run again

### PR DESCRIPTION
**Pull request by GarreltMock**
Hey Markus,
ich arbeite mit Aileen zusammen bei Lotum und sie hat mir euer cooles Spiel gezeigt.
Leider lief es ja so wie es war nicht mehr.
Das Game ist aber so cool und charmant, dass ich dachte wir sollten es wieder zum Laufen kriegen.

Props für die coolen Spiele die ihr damals gemacht habt. Hat Spaß gemacht sie zu spielen.

Liebe Grüße

### CODE REVIEW

**Review by mtib — APPROVED** [review]

**Comment by GarreltMock** [comment]
Nice :) Ich kann es leider nicht mergen 🙈

**Comment by mtib** [comment]
Thanks for contributing! If there's more restoration you want to do on the codebase I can make you (and Aileen, if she has a new GitHub account / never was added) a contributor.

**Comment by GarreltMock** [comment]
My pleasure.
I actually don't know Aileens Github account 😄

**Comment by GarreltMock** [comment]
Oh yes. I see there is one more issue :) 
Would be nice, if you could make me contributor 🙏

**Comment by mtib** [comment]
Just set up GitHub actions and fixed the HTTPS issue: automatically deployed to http://ludum37.mtib.dev/ now.

**Comment by GarreltMock** [comment]
Ah nice :) Thanks

**Comment by mtib** [comment]
Added @abhededam as a contributor, can you outline what you want to change? Because if you plan to make major changes I'd rather migrate the repository to a organisation we all have shared access to (because otherwise I'd ofc be liable for anything you do, as this is currently on my personal account).

**Comment by GarreltMock** [comment]
I have no plans actually.
Just wanted to make it run again. So I don't really need contributor rights 👍 
The issue I mentioned was the HTTPS thing you fixed

**Comment by mtib** [comment]
Awesome. If there is any interested in shared ownership I can set up the organisation, just let me know.

**Comment by GarreltMock** [comment]
Thanks for the help Markus :)

**Comment by LFalch** [comment]
Thank you for the interest in our game :)

**Pull request merged**
